dist: trusty

os:
- linux

language: go

go:
- 1.9
- tip

matrix:
  allow_failures:
  - go: tip

before_install:
- go get github.com/Masterminds/glide
- go get github.com/mattn/goveralls

install:
- glide install --strip-vendor

script:
- goveralls -service=travis-ci
