dist: trusty

os:
- linux

language: go

go:
- 1.7
- tip

before_install:
- go get github.com/Masterminds/glide
- go get github.com/mattn/goveralls

install:
- glide install

script:
- goveralls -service=travis-ci
